name: workflow.yml
on:
  push:
    branches:
      - github_dev # Auf dem dev-Branch triggern

jobs:
  build-root:

    runs-on: ubuntu-latest
    outputs:
        ARTIFACT_ID: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}
        VERSION: ${{ steps.extract-maven-coordinates.outputs.VERSION }}
        GROUP_PATH: ${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        overwrite-settings: 'false'

    - name: Extract Maven coordinates (Parent)
      id: extract-maven-coordinates
      run: |
          GROUP_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.groupId -q -DforceStdout)
          ARTIFACT_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -f pom.xml -Dexpression=project.version -q -DforceStdout)
          GROUP_PATH=${GROUP_ID//./\/}
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "GROUP_PATH=$GROUP_PATH" >> $GITHUB_OUTPUT

    - name: Build Root Pom
      run: mvn -B -N clean package install --file pom.xml -Pgithub

    - name: Upload local Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}-${{ steps.extract-maven-coordinates.outputs.VERSION }}
        path: ~/.m2/repository/${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}/
        retention-days: 1

  build-sdk:
    runs-on: ubuntu-latest
    needs:
      - build-root
    outputs:
      ARTIFACT_ID: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}
      VERSION: ${{ steps.extract-maven-coordinates.outputs.VERSION }}
      GROUP_PATH: ${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Download parent pom repository
      uses: actions/download-artifact@v4
      with:
          name:  ${{ needs.build-root.outputs.ARTIFACT_ID }}-${{ needs.build-root.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-root.outputs.GROUP_PATH }}/

    - name: Extract Maven coordinates (njams-sdk)
      id: extract-maven-coordinates
      run: |
        GROUP_ID=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.groupId -q -DforceStdout)
        ARTIFACT_ID=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.artifactId -q -DforceStdout)
        VERSION=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.version -q -DforceStdout)
        GROUP_PATH=${GROUP_ID//./\/}
        echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "GROUP_PATH=$GROUP_PATH" >> $GITHUB_OUTPUT

    - name: Build SDK with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file njams-sdk/pom.xml -Pgithub -Dsonar.projectKey=IntegrationMatters_njams-sdk

    - name: Upload local Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}-${{ steps.extract-maven-coordinates.outputs.VERSION }}
        path: ~/.m2/repository/${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}/
        retention-days: 1

  build-client-sample:
    runs-on: ubuntu-latest
    needs:
      - build-root
      - build-sdk
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    -   name: Download parent pom repository
        uses: actions/download-artifact@v4
        with:
            name: ${{ needs.build-root.outputs.ARTIFACT_ID }}-${{ needs.build-root.outputs.VERSION }}
            path: ~/.m2/repository/${{ needs.build-root.outputs.GROUP_PATH }}/

    - name: Download njams-sdk repository
      uses: actions/download-artifact@v4
      with:
          name: ${{ needs.build-sdk.outputs.ARTIFACT_ID }}-${{ needs.build-sdk.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-sdk.outputs.GROUP_PATH }}/

    - name: Build client sample
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B clean package -U --file njams-sdk-sample-client/pom.xml -Pgithub

