name: Build nJAMS SDK
on:
  push:
    branches:
      - github_dev # Trigger only on github_dev

jobs:
  build-root:

    runs-on: ubuntu-latest
    outputs:
        ARTIFACT_ID: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}
        VERSION: ${{ steps.extract-maven-coordinates.outputs.VERSION }}
        GROUP_PATH: ${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        overwrite-settings: 'false'

    - name: Extract Maven coordinates (Parent)
      id: extract-maven-coordinates
      run: |
          GROUP_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.groupId -q -DforceStdout)
          ARTIFACT_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -f pom.xml -Dexpression=project.version -q -DforceStdout)
          GROUP_PATH=${GROUP_ID//./\/}
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "GROUP_PATH=$GROUP_PATH" >> $GITHUB_OUTPUT

    - name: Build Root Pom
      run: mvn -B -N clean package install --file pom.xml -Pgithub

    - name: Upload local Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}-${{ steps.extract-maven-coordinates.outputs.VERSION }}
        path: ~/.m2/repository/${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}/
        retention-days: 1

  run-checkstyle:
    runs-on: ubuntu-latest
    needs: build-root

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Create checkstyle report
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B site --file njams-sdk/pom.xml -Pgithub,checkstyle

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: njams-sdk/target/site

    - name: Check on Error
      run: mvn -B validate --file njams-sdk/pom.xml -Pgithub,checkstyle

  create-java-doc-for-njams-sdk:

    runs-on: ubuntu-latest
    needs: build-root

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          overwrite-settings: 'false'

      - name: Build JavaDoc
        run:
          mvn -B generate-sources javadoc:javadoc --file pom.xml

  build-sdk:
    runs-on: ubuntu-latest
    needs:
      - build-root
      - run-checkstyle
      - create-java-doc-for-njams-sdk
    outputs:
      ARTIFACT_ID: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}
      VERSION: ${{ steps.extract-maven-coordinates.outputs.VERSION }}
      GROUP_PATH: ${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Download parent pom repository
      uses: actions/download-artifact@v4
      with:
          name:  ${{ needs.build-root.outputs.ARTIFACT_ID }}-${{ needs.build-root.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-root.outputs.GROUP_PATH }}/

    - name: Extract Maven coordinates (njams-sdk)
      id: extract-maven-coordinates
      run: |
        GROUP_ID=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.groupId -q -DforceStdout)
        ARTIFACT_ID=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.artifactId -q -DforceStdout)
        VERSION=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.version -q -DforceStdout)
        GROUP_PATH=${GROUP_ID//./\/}
        echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "GROUP_PATH=$GROUP_PATH" >> $GITHUB_OUTPUT

    - name: Build SDK with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file njams-sdk/pom.xml -Pgithub -Dsonar.projectKey=IntegrationMatters_njams-sdk -DrevisionNumberPlugin.revision=${{ github.run_number }} -DscmBranch=${{ github.ref_name }} -DscmCommit=${{ github.sha }}

    - name: Upload Unit-Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: junit-reports
        path: njams-sdk/target/surefire-reports/

    - name: Upload Integration-Test Reports
      uses: actions/upload-artifact@v4
      with:
          name: integration-reports
          path: njams-sdk/target/failsafe-reports/

    - name: Upload local Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.extract-maven-coordinates.outputs.ARTIFACT_ID }}-${{ steps.extract-maven-coordinates.outputs.VERSION }}
        path: ~/.m2/repository/${{ steps.extract-maven-coordinates.outputs.GROUP_PATH }}/
        retention-days: 1

  trivy-scan:
    runs-on: ubuntu-latest
    needs:
      - build-sdk
    steps:
      - name: Download njams-sdk repository
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-sdk.outputs.ARTIFACT_ID }}-${{ needs.build-sdk.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-sdk.outputs.GROUP_PATH }}/

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: /home/runner/.m2/repository/${{ needs.build-sdk.outputs.GROUP_PATH }}/${{ needs.build-sdk.outputs.ARTIFACT_ID }}/${{  needs.build-sdk.outputs.VERSION  }}/${{ needs.build-sdk.outputs.ARTIFACT_ID }}-${{  needs.build-sdk.outputs.VERSION  }}.jar
          format: table
          exit-code: 1   # schl√§gt fehl, wenn Vulnerabilities gefunden werden
          severity: CRITICAL,HIGH

  build-client-sample:
    runs-on: ubuntu-latest
    needs:
      - build-root
      - build-sdk
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    -   name: Download parent pom repository
        uses: actions/download-artifact@v4
        with:
            name: ${{ needs.build-root.outputs.ARTIFACT_ID }}-${{ needs.build-root.outputs.VERSION }}
            path: ~/.m2/repository/${{ needs.build-root.outputs.GROUP_PATH }}/

    - name: Download njams-sdk repository
      uses: actions/download-artifact@v4
      with:
          name: ${{ needs.build-sdk.outputs.ARTIFACT_ID }}-${{ needs.build-sdk.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-sdk.outputs.GROUP_PATH }}/

    - name: Build client sample
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B clean package -U --file njams-sdk-sample-client/pom.xml -Pgithub

