name: workflow.yml
on:
  push:
    branches:
      - github_dev # Auf dem dev-Branch triggern

jobs:
  build-root:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        overwrite-settings: 'false'

    - name: Extract Maven coordinates (Parent)
      run: |
        echo "GROUP_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
        echo "ARTIFACT_ID=$(mvn help:evaluate -f pom.xml -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
        echo "VERSION=$(mvn help:evaluate -f pom.xml -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build Root Pom
      run: mvn -B -N clean package install --file pom.xml -Pgithub

    - name: Upload local Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_ID }}-${{ env.VERSION }}
        path: ~/.m2/repository/${{ env.GROUP_ID }}/
        retention-days: 1

  build-sdk:
    runs-on: ubuntu-latest
    needs:
      - build-root
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Download local Maven repository
      uses: actions/download-artifact@v4
      with:
          name:  ${{ needs.build-root.steps.extract.outputs.ARTIFACT_ID }}-${{ needs.build-root.steps.extract.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-root.steps.extract.outputs.GROUP_ID }}/

    - name: Extract Maven coordinates (njams-sdk)
      run: |
        echo "GROUP_ID=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
        echo "ARTIFACT_ID=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
        echo "VERSION=$(mvn help:evaluate -f njams-sdk/pom.xml -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build SDK with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file njams-sdk/pom.xml -Pgithub -Dsonar.projectKey=IntegrationMatters_njams-sdk

    - name: Upload local Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_ID }}-${{ env.VERSION }}
        path: ~/.m2/repository/${{ env.GROUP_ID }}/
        retention-days: 1

  build-client-sample:
    runs-on: ubuntu-latest
    needs:
      - build-sdk
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Download local Maven repository
      uses: actions/download-artifact@v4
      with:
          name: ${{ needs.build-sdk.steps.extract.outputs.ARTIFACT_ID }}-${{ needs.build-sdk.steps.extract.outputs.VERSION }}
          path: ~/.m2/repository/${{ needs.build-sdk.steps.extract.outputs.GROUP_ID }}/

    - name: Build client sample
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B clean package -U --file njams-sdk-sample-client/pom.xml -Pgithub

